{% set name = "glib-networking" %}
{% set version = "2.72.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 100aaebb369285041de52da422b6b716789d5e4d7549a3a71ba587b932e0823b

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - gettext     # [osx and (build_platform != target_platform)]
    - meson
    - ninja
    - pkg-config
  host:
    - gettext  # [osx]
    - glib
    - openssl
    - zlib
  run:
    - gettext
    # The post-link scripts need glib
    - glib  >=2.70.0
    - openssl

test:
  commands:
    - test -f ${PREFIX}/lib/gio/modules/libgioopenssl.so                  # [unix]
    - if not exist %LIBRARY_LIB%\\gio\\modules\\gioopenssl.dll exit 1     # [win]
  downstreams:
    - libsoup

about:
  home: https://gitlab.gnome.org/GNOME/glib-networking
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Network related modules for glib

extra:
  recipe-maintainers:
    - tschoonj
