{% set name = "glib-networking" %}
{% set version = "2.68.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 0b235e85ad26b3c0d12255d0963c460e5a639c4722f78e2a03e969e224b29f6e

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
  host:
    - glib
    - openssl
  run:
    - gettext
    # The post-link scripts need glib
    - glib  >=2.68.0
    - openssl

test:
  commands:
    - test -f ${PREFIX}/lib/gio/modules/libgioopenssl.so                  # [unix]
    - if not exist %LIBRARY_LIB%\\gio\\modules\\gioopenssl.dll exit 1     # [win]
  downstreams:
    - libsoup

about:
  home: https://gitlab.gnome.org/GNOME/glib-networking
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Network related modules for glib

extra:
  recipe-maintainers:
    - tschoonj
