{% set name = "glib-networking" %}
{% set version = "2.78.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 52fe4ce93f7dc51334b102894599858d23c8a65ac4a1110b30920565d68d3aba

build:
  number: 0
  run_exports:
    # Following glib's pinnings
    - {{ pin_subpackage('glib-networking') }}

requirements:
  build:
    - {{ compiler('c') }}
    - gettext     # [osx and (build_platform != target_platform)]
    - meson
    - ninja
    - pkg-config
  host:
    - gettext  # [osx]
    - glib
    - openssl
    - zlib
  run:
    # The post-link scripts need glib
    - glib  {{ version_majmin }}

test:
  commands:
    - test -f ${PREFIX}/lib/gio/modules/libgioopenssl.so                  # [unix]
    - if not exist %LIBRARY_LIB%\\gio\\modules\\gioopenssl.dll exit 1     # [win]
  downstreams:
    - libsoup

about:
  home: https://gitlab.gnome.org/GNOME/glib-networking
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: Network related modules for glib

extra:
  recipe-maintainers:
    - tschoonj
